[project]
name = "project-crewai-agent"
version = "0.1.0"
description = "Project to create AI Agent, Multi Agents"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "crewai-tools>=1.4.1",
    "crewai[google-genai]>=1.4.1",
    "serpapi>=0.1.5",
]
